### ISSUE TITLE
logo + artwork 

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018#1]
_Let's try using github this time to organise tasking instead of trello like last year._ 

@rasagy - I know we chatted a bit about this. Do you think this is something you can help with? For the next edition we aren't going to do a logo contest. 

Here're some links from previous editions:
* SOTM Asia 2017 http://wiki.openstreetmap.org/wiki/State_Of_The_Map_Asia_2017/Logo_entries
* SOTM Asia 2016 http://wiki.openstreetmap.org/wiki/State_of_the_Map_Asia_2016
* SOTM Africa 2017 http://wiki.openstreetmap.org/wiki/State_of_the_Map_Africa_2017/Logo_Entries
* SOTM Global 2016 http://wiki.openstreetmap.org/wiki/State_Of_The_Map_2016/Logo_entries

Let me know! Happy to speak on the phone if you'd like.

**Comment by rasagy** [comment]
A little late, but here’s what I worked on:

We started with three directions (Rangoli, Rickshaw + cameras, Multi-lingual letters). I narrowed  down to the first idea — making a circular, symmetric logo which represents the unique rangoli style from India and also resembles the east asian mandalas.

I restricted myself to only use the 3 basic geometry types on OSM (points, lines, polygons) and the marker icon to create a simple logo. Using only a few elements means that even at small sizes, the pattern is still visible.

![geo-mandala-concept](https://user-images.githubusercontent.com/1117531/36828250-97a4a2b8-1d3e-11e8-97d8-ecb61efe2cd5.png)

Based on some feedback, the logo with the globe and lines moving outward seems like the best pick — it’s a bit more direct/clearly related to OSM.

For the color palette, I first took the natural rangoli colors (pastel shades of red & yellow) and narrowed down on the font Dosis that pairs well with this style (rounded corners, good set of weights, and looks great next to the logo).

Here’s how the logo looks like:

![gm-red_3-dos](https://user-images.githubusercontent.com/1117531/36828306-f9fcb040-1d3e-11e8-9c89-1cbcdc843c04.png)
![yellow - v](https://user-images.githubusercontent.com/1117531/36828296-ec5e8bfc-1d3e-11e8-9904-85216d25ca4a.png)

Alternate color palette that we decided to not use:

![gm-purple_3-dos](https://user-images.githubusercontent.com/1117531/36828329-11b41c96-1d3f-11e8-993c-026c45a01a65.png)

**Comment by geohacker** [comment]
@rasagy - thank you for your work on this. This changes a lot of how we approach the event from now - including the conversations we're able to have. 🙇  ✌️

**Comment by satyaakam** [comment]
@rasagy cool Please share all the assets in raw also let us know the fonts to use and CMYK

**Comment by jinalfoflia** [comment]
Committed the logo and artwork files to the repository - https://github.com/sotm-asia/sotm-asia-2018/tree/master/logo+artwork

cc: @maning @geohacker @tridip1931 @rasagy @satyaakam

**Comment by rasagy** [comment]
[Updated the repo](https://github.com/sotm-asia/sotm-asia-2018/tree/master/logo%2Bartwork) with logo files (png, svg, ai etc.) and the font files for [Dosis](https://fonts.google.com/specimen/Dosis).

The logo uses the weights `SemiBold` and `Regular`.

Colors: Red: `#F16365` and Yellow: `#FCF5A7`

**Comment by rasagy** [comment]
Also pushed a wide variant to the logo [here](https://github.com/sotm-asia/sotm-asia-2018/blob/master/logo%2Bartwork/logo/svg/logo-text-wide.svg).

![logo-text-white-bg-wide](https://user-images.githubusercontent.com/1117531/37135809-01ad78c0-22c5-11e8-9a14-f7858150c344.png)

**Comment by jinalfoflia** [comment]
No next actions here, closing this! Thanks so much @rasagy for this amazing logo and artwork! 💥
