### ISSUE TITLE
A wiki page for SotM Asia

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018#12]
Similar to the [SotM International (Milan)](https://wiki.openstreetmap.org/wiki/State_of_the_Map_2018), we need to have a wiki page for SotM Asia as well. Will start working on the draft for it and once the artwork is ready, will go ahead and create the page.

cc: @geohacker

**Comment by chtnha** [comment]
@jinalfoflia Here is already existing wiki page for sotm asia 2018 https://wiki.openstreetmap.org/wiki/State_of_the_Map_Asia_2018

**Comment by jinalfoflia** [comment]
Thank you @chtnha for keeping the wiki updated. 🙇‍♀️ 
Closing this!
