### ISSUE TITLE
Planning for Call for Proposal

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018#16]
Writing this ticket to prepare for Call for Proposals. The sections given below are the action items that are required to get this going.

### Announcing the Call for Proposals

- [x] @maning to lead out and form the proposal review committee 
- [x] Set up a timeline for accepting, reviewing and announcing the selected talks + workshops for the conference
Here are the **tentative dates** that I have come up with:
    - Announcing the CfP -> **~~April 1st~~** -> Tentatively: 4th April
    - Deadline to Submit the proposals -> **~~June 24th~~** -> June 10th
    - Review proposals -> **~~2nd July~~** -> TBD -- Based on the planning committee 
    - Share the review results with the submitters and seek for confirmation on participation -> **~~6th July~~** -- 26th June

### Deciding the different categories and duration of the session by 

- [x] Decide the different information fields that we’d want the submitter to fill  
- [x] Deciding the duration of talks and workshops
      **Suggestions:**
    - Country presentation - **10 mins**
    - Lightning talk - **5 mins**
    - Talk - **15 mins**
    - Workshop - **75 mins**
    - Panel

- [x] Finalise the list of categories that we’d want to offer to the submitter
    - Cartography / visualization
    - Data creation
    - Data use and analysis
    - Intro to OSM
    - Technical / IT systems
    - Humanitarian
    - Education / documentation
    - Local community / diversity
    - Organization and legal
    - Transport and planning
    - Academic
**Note: This is not the final list, would be happy to have recommendations that are unique to Asia**

### Designing the submitter form

- [x] Designing a google form that accommodates all the above
- [x] Have design team work on/approve on the design theme used in the form
- [x] Link the form to the website

### Comms

- [x] Write the blog post announcing the CfP
- [x] Have a comms plan to tweet and share it on different Asian communities FB pages at different intervals of time

cc:  @sotm-asia/sotm-asia-core

**Comment by geohacker** [comment]
Thank you for getting this started @jinalfoflia!

> Finalise the list of categories that we’d want to offer to the submitter

I think we want to keep the list small but relevant to the conversations. How about something like this:

* Cartography / visualization / analysis
* Data creation
* Humanitarian
* Education / documentation
* Local community / diversity
* Transport / planning
* Governance / public policy

**Comment by maning** [comment]
Adding one more.

* Surprise us!

**Comment by jinalfoflia** [comment]
> Set up a timeline for accepting, reviewing and announcing the selected talks + workshops for the conference
> Here are the tentative dates that I have come up with:
> Announcing the CfP -> April 1st
> Deadline to Submit the proposals -> June 24th
> Review proposals -> 2nd July
> Share the review results with the submitters and seek for confirmation on participation -> 6th July

Are we all 👍 with this timeline?

> Desing a google form that accommodates all the above
> Have design team work on/approve on the design theme used in the form

Here is the submitter form: https://goo.gl/forms/VkOKee34xfzyoylI3 (cc: @geohacker @maning)

@rasagy @tridip1931 -- would love your feedback on this, feel free to modify it based on the website.

**Comment by rasagy** [comment]
Small feedback around copy:
>Sessions and your responses in this form can be in English.

_can be_ or should be? Can makes sense if there are options (can be in English, Kannada, Hindi), not for a single option.

>I am female

We should make this more inclusive for non-binary attendees.

>If there is anything else we should now, write it here.

_know_ and not _now_, and we should make this more explicit (anything else that you’ll need for your session, or want to let us know).

Can we link to the scholarship form from the CFP form? (Either in the end or at the point where we ask the question).

**Comment by jinalfoflia** [comment]
@rasagy thanks so much for the feedback! 🙇‍♀️ Have made the suggested changes.

>Can we link to the scholarship form from the CFP form? (Either in the end or at the point where we ask the question).

Yes, have added a question: `Would you require a scholarship?`, if yes, then there is a link to the Call for Scholarship (CfS) form. Tejas is working on the CfS form.

**Comment by tridip1931** [comment]
My 2 _rupiya_. Please feel free to ignore this:
>I will not be able to attend without my scholarship application approved (note: this is a separate form)
>This will be my first time speaking at the OpenStreetMap Asia conference

Should we reframe ☝️  to more shorter sentences:
- Need scholarship. (Learn more)
- First time speaker at OSM Asia conference

**Comment by govvin** [comment]
What do you think off adding the following under the conditions of attendance/presentation?

[ ] - I will present my session(s) as accepted by the organizers.
[ ] - I grant permission to State of the Map Asia to post my session description, biography and copy presentation deck to tour website, and use this information in any of our marketing materials.
[ ] - I will adhere to the the State of the Map Asia Code of Conduct (see <URL>).

**Comment by jinalfoflia** [comment]
Thank you team, the Call for Proposal was announced - https://medium.com/state-of-the-map-asia/call-for-proposal-ce6a93ec9c64, will open up new tickets for next actions, closing this for now!

**Comment by govvin** [comment]
Kindly consider adding a email confirmation when an application is submitted. There's a Form [plugin](https://chrome.google.com/webstore/detail/form-confirmation-emails/jpcbhpmhfdheaohgidhjgjgfhocninfn) for that.

**Comment by jinalfoflia** [comment]
@govvin @tridip1931 have added confirmation email for CfS and CfP. Thanks for the suggestion 🙇‍♀️
