### ISSUE TITLE
Sponsorship Deck

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018#2]
We'll fork what SOTM global 2018 is doing and prepare what meets our needs. @jinalfoflia is running point.

**Comment by geohacker** [comment]
@jinalfoflia this is the deck that sotm 2018 is using https://2018.stateofthemap.org/Sponsorship2018v2b.pdf

**Comment by satyaakam** [comment]
@geohacker do we have  source for this one to modify and work on with

**Comment by geohacker** [comment]
I can ask Rob, but we can also just put together one no? Should be pretty straightforward. 
@jinalfoflia is working on this.

**Comment by jinalfoflia** [comment]
Here is the first draft - 
[sotm-asia-2018.pdf](https://github.com/sotm-asia/sotm-asia-2018/files/1766061/sotm-asia-2018.pdf)

Things to be done:

- [ ] Styling the deck based on the logo (Artwork)
- [ ] Some more iterations on the draft

cc: @geohacker @satyaakam

**Comment by geohacker** [comment]
Thank you @jinalfoflia!

@rasagy @maning @planemad @poornibadrinath - want to post ideas from our catchup earlier today? It'll be great to get this in shape latest of this weekend. 

@satyaakam - would love if you can help!

**Comment by geohacker** [comment]
Quick feedback based on different conversations:
* we should probably only do gold 15k, silver 10k, bronze 5k, community 1k.
* @rasagy will help expand on overall realestate we can offer
* we don't know yet if we'll be able to offer an exhibition space - what else can we offer in place of this?

**Comment by jinalfoflia** [comment]
Thank you for sharing the feedback, will iterate the draft based on this and also would need @rasagy's help in maybe styling it.

**Comment by satyaakam** [comment]
@jinalfoflia can you share the source document of the deck to work on

**Comment by jinalfoflia** [comment]
>@jinalfoflia can you share the source document of the deck to work on

@satyaakam have shared the files and other images that we can use for the deck. I'm working on refining the content in parallel with you designing the slide deck.

**Comment by geohacker** [comment]
@satyaakam @jinalfoflia how are we doing here? We should start sending the deck out on Monday to folks who have requested. Let me know if I can help with anything. Thank you!

**Comment by satyaakam** [comment]
@geohacker yes we are ready with the template , i have outlined with cations @jinalfoflia can fill in the details. Should be ready by tomorrow

**Comment by jinalfoflia** [comment]
>@geohacker yes we are ready with the template , i have outlined with captions @jinalfoflia can fill in the details. Should be ready by tomorrow

@geohacker @satyaakam working on it and will be posting the ready one with contents by EOD.

**Comment by jinalfoflia** [comment]
@geohacker @satyaakam here is the deck - https://docs.google.com/presentation/d/1fz4BgXw7eYcpaFla1qRKN836c0v3-SNUi9yOn3lXYJU/edit?usp=sharing

There are a couple of slides that need 👀

**Comment by jinalfoflia** [comment]
Here is the link to the presentation - https://docs.google.com/presentation/d/e/2PACX-1vRlh4Pnmp9SgUXAjgP6kxvqlOLRAoJjYHZYP_8_5arhgGe2v8AjSNX60NzVVZZ3oes8ZAIzjVowl8Qb/pub?start=true&loop=false&delayms=3000

cc: @geohacker @maning @satyaakam @rasagy

**Comment by jinalfoflia** [comment]
No next actions here. Will re-open if needed.
