### ISSUE TITLE
Tiered-pricing for tickets?

### ISSUE THREAD

**Issue by govvin** [sotm-asia/sotm-asia-2018#23]
Sajjad mentioned this in the meeting yesterday, but my audio was choppy so I may have missed a lot of what was said.

I believe that we should seriously consider ticket sales as a way to cover some of the expenses for SotM Asia events. While we don't expect it to cover most of the expenses, we can at least reduce the amount of money organizers need to raise to make the event possible.

We would also want the event sessions to be accessible to as many people as possible. So, how about a tiered-pricing structure for tickets? Additional reading: [The psychology of free vs. paid events](http://shanereiser.com/to-charge-or-not-to-charge-the-psychology-of-free-vs-paid-events/).

- Tier 1 - Pay what you like,with a **recommended** minimum amount. Access to all sessions.
- Tier 2 - X amount, and ticket holder gets a nice, printed Certificate of Participation.
- Tier 3 - Y amount, Certificate + T-shirt (with the advantage of knowing how many t-shirts to order, for whatever size.)
- Tier 4 - Z amount, Certificate + T-shirt + Free lunch + Happy Hour

Hopefully, the ticket prices can cover the cost of the "freebies", with no consideration for mark-ups.

Also, with tickets, our "Corporate ticket" offer to sponsors makes more sense. We can also offer special discount codes to members of our partner organizations.

Another thing to consider is the administrative cost, and extra effort to do this. 

What do you think?

**Comment by geohacker** [comment]
We're going ahead with single tier because of taxes and ease of receiving money.
