### ISSUE TITLE
Medium Blog for the Website

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018#24]
Reference: https://github.com/sotm-asia/sotm-asia-2018/issues/21 and https://github.com/sotm-asia/sotm-asia-2018/issues/10

It is important for to have a dedicated space to announce all our event-related announcements, testimonials, etc as blog posts as well as have a way of sharing the content for cross-posting. We have decided to host our blog on Medium.

### Next action[s]

- [x] @jinalfoflia to create the Medium account for OSM Asia 

cc: @sotm-asia/sotm-asia-core

**Comment by jinalfoflia** [comment]
>@jinalfoflia to create the Medium account for OSM Asia

Here is the publication link: https://medium.com/state-of-the-map-asia/
Here is the link to the Medium profile: https://medium.com/@osmasia

cc: @rasagy @tridip1931 @geohacker

**Comment by jinalfoflia** [comment]
The blog and publication are up. 🚀 Minor tweaks can be done as we go ahead in using them, closing this ticket for now. I have only added few folks as editors on the publication page, please let me know if you need access too.

PS: You need to have a Medium account for me to add you as an editor

**Comment by tridip1931** [comment]
Do you need help with assets @jinalfoflia? 
I can help you with the cover image and profile pic for medium account.

**Comment by jinalfoflia** [comment]
>Do you need help with assets @jinalfoflia?
I can help you with the cover image and profile pic for medium account.

Thanks for the help @rasagy @tridip1931. We can iterate over the blog as and when we have more posts.
