### ISSUE TITLE
Social media accounts

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018#3]
Let's consolidate social media accounts. 

cc @satyaakam @jinalfoflia

**Comment by jinalfoflia** [comment]
The facebook pages of most of the Asian OSM communities 

- [ ] India https://www.facebook.com/groups/mappingindia/
- [ ] Bangladesh https://www.facebook.com/groups/osmbd/
- [ ] Sri Lanka https://www.facebook.com/groups/142058222659672/
- [ ] Bhutan https://www.facebook.com/groups/osmbhutan/
- [ ] Myanmar https://www.facebook.com/groups/osmmm/
- [ ] Indonesia https://www.facebook.com/groups/osm.id/
- [ ] Philliphines https://www.facebook.com/OSMPH/
- [ ] Japan https://www.facebook.com/groups/osmjapan/
- [ ] Vietnam https://www.facebook.com/osmvncommunity/
- [ ] Mongolia https://www.facebook.com/groups/OSM.Mongolia/
- [ ] Taiwan https://www.facebook.com/groups/OpenStreetMap.TW/

### Next action[s]

We donot have a State of the Map Asia Twitter account

- [ ] @jinalfoflia to create a twitter account 

@geohacker do we have an email ID that we are intending to use for communications?

**Comment by geohacker** [comment]
@jinalfoflia good question - I don't think we've one. Unless @mapconcierge or @maning set it up? We can setup one or give people access to their preferred email accounts - whatever you think is best.

**Comment by jinalfoflia** [comment]
@geohacker have set up an account for now - `stateofthemapasia@gmail.com` as others were already taken. Did not think of using a personal one as this could be an email address that could be used in the future SotM Asia conferences too. Will go ahead and create a twitter account using the same email address.

**Comment by kshitizkhanal7** [comment]
https://docs.google.com/spreadsheets/d/1TmwsTKomK486l454NB9H7R5SXvMm6C_ZmTHVKz8HtMI/edit#gid=0
Points of contact in different countries of Asia

**Comment by govvin** [comment]
By the way, when you ask permission from participants when you collect data from the, please ask for permission to specifically share the same with the  SotM Asia "permanent committee"/team that goes with the transition between hosting countries . The reason we shared very little participant data from 2016 was we overlooked this explicit permission.

**Comment by jinalfoflia** [comment]
### State of the Map Asia's different social media accounts:

- [YouTube](https://www.youtube.com/channel/UCR7PMzU0l__u8Pt73QyHWAQ) - for live streaming during the conference

### Outreach:

- [Medium profile](https://medium.com/@osmasia)
- [Medium SotM Asia publication](https://medium.com/state-of-the-map-asia/) 
- [Twitter](https://twitter.com/SotmAsia)
- [All the regional FB groups mentioned in the comment above](https://github.com/sotm-asia/sotm-asia-2018/issues/3#issuecomment-363284228)

Closing this and following up here - https://github.com/sotm-asia/sotm-asia-2018/issues/21
