### ISSUE TITLE
Money Channel

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018#6]
💵 💵  + 🇮🇳 

Everyone knows this is a pain, so we're going to have to figure this out. Since OSM India isn't a registered entity or have FCRA clearance to bring money from outside the country, I'm looking for options:

* [x] Datameet - reached out, no FCRA
* [x] CIS - FCRA yes, reaching out shortly
* [ ] India Open Data Association - FCRA yes, reaching out after CIS.

We'll offer co-branding for their service. I'll keep this ticket posted.

**Comment by satyaakam** [comment]
@geohacker CIS i found in past to be slow in paper work , go with IODA known folks , quick turnaround time.

**Comment by geohacker** [comment]
@satyaakam I hear you. I'm talking to Sunil and Sumandro, will post details soon. I'd prefer CIS because it's convenient that they are in Bangalore.

**Comment by geohacker** [comment]
Sunil says they will be happy to do this on our behalf - they will need a 10% markup for covering administrative costs. I think this is fair, and it'll be easy for one of us to follow up based in Bangalore. CIS has a track record of being able to support communities like ours.

**Comment by geohacker** [comment]
We're going ahead with CIS. I'll follow up with more details.
