### ISSUE TITLE
Code of Conduct for the conference

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018#9]
We had a code of conduct for SotM Asia 2017 - http://2017.stateofthemap.asia/code-of-conduct.html

Let's re-look into the drafting of this and modify it based on the requirements. 

### Next actions

- [x] Re-look into the previous draft and go ahead with edits
- [x] Refer to the SotM International (Milan)'s code of conduct and see pieces that fit well with the current one.
- [x] Re-draft the CoC based on the suggestions and edits

cc: @geohacker

**Comment by jinalfoflia** [comment]
Here is the draft of the CoC - https://docs.google.com/document/d/1g_WL6R1C7W7QwAdwYxFAk-77xznTJWAPeqq342u82tE/edit?usp=sharing

Documents referred:

- https://2018.stateofthemap.org/codeofconduct/
- http://2017.stateofthemap.asia/code-of-conduct.html

cc: @geohacker @tridip1931

**Comment by geohacker** [comment]
@jinalfoflia I think this reads great and has very good coverage across venues and events. I'm a 👍. 
@tridip1931 when you're ready, let's get this on the website.

Thank you!

**Comment by govvin** [comment]
Folks, do we need a TLDR; version? Snipped from the AAG progam:

Ideas and information are exchanged most effectively at the State of the Map Asia events in an atmosphere free of abuse or harassment, and characterized by courtesy and respect. To that end, the SotM Asia expects all individuals who attend to conduct themselves in a manner that establishes an atmosphere free from discriminatory practices. The full Code of Conduct is available <<link>>.

Do you think this adequately covers our full COC? (which I'm hoping we're not replacing, and users must agree to when registering for participation.)

**Comment by rasagy** [comment]
Oops, missed cross posting [my comment from the CoC PR](https://github.com/sotm-asia/sotm-asia-2018-website/pull/14#issuecomment-375623571) here — agree with @govvin on having a shorter, summarized version of CoC on the website first, and following it with the more detailed version below it.

@jinalfoflia would love your 👀 on the summary @govvin posted above! 🙇

**Comment by jinalfoflia** [comment]
>Ideas and information are exchanged most effectively at the State of the Map Asia events in an atmosphere free of abuse or harassment, and characterized by courtesy and respect. To that end, the SotM Asia expects all individuals who attend to conduct themselves in a manner that establishes an atmosphere free from discriminatory practices. The full Code of Conduct is available <>.
>Do you think this adequately covers our full COC? (which I'm hoping we're not replacing, and users must agree to when registering for participation.)

Thanks for this TLDR version of the CoC @govvin. This looks great. I agree this should be something the users must agree before registering. 

@rasagy trying to make changes according to your suggestions. @tridip1931 we have the summary version of the CoC here, can you please add it to the website? Thank you!

**Comment by geohacker** [comment]
Thank you for this @govvin @jinalfoflia @rasagy!

**Comment by jinalfoflia** [comment]
The page is live - http://stateofthemap.asia/coc.html ✨ 

Thank you @tridip1931 🚀 

No next actions here, closing this!

**Comment by geohacker** [comment]
Thanks everyone!

**Comment by bkowshik** [comment]
> The page is live - http://stateofthemap.asia/coc.html

Getting a `http 404` when I visit this page. This is also linked on the talk submission form.

<img width="1262" alt="screen shot 2018-06-18 at 17 15 57" src="https://user-images.githubusercontent.com/2899501/41534349-e36f6a4c-731b-11e8-88bd-1e0c8ac9e606.png">

**Comment by jinalfoflia** [comment]
@bkowshik thank you for flagging this, there were many changes to the website post the CfP form was released. Changing the link, right away.
